/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_estructuraa;

import java.awt.Label;
import javax.swing.JFrame;

/**
 *
 * @author bryan
 */
public class Loggin extends javax.swing.JFrame {

    /**
     * Creates new form Loggin
     */
    public Loggin() {
        initComponents();
        this.setResizable(false);
        this.setSize(1153,680);
        this.setLocationRelativeTo(null);
        Fondo2.setVisible(false); 
        Fondo4.setVisible(false);
        Fondo5.setVisible(false);
        Menu.setVisible(false);
        panel_ingreso.setVisible(false);
        cambio_ecena_login cm = new cambio_ecena_login(Fondo2,Fondo3 ,panel_ingreso);
        cm.start();
        
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Fondo5 = new javax.swing.JLabel();
        panel_ingreso = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Fondo2 = new javax.swing.JLabel();
        Fondo4 = new javax.swing.JLabel();
        Fondo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Menu.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102,150));
        jPanel2.setLayout(null);
        Menu.add(jPanel2);
        jPanel2.setBounds(90, 580, 1060, 70);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102,150));
        jPanel4.setLayout(null);
        Menu.add(jPanel4);
        jPanel4.setBounds(0, 0, 90, 650);

        jPanel3.setBackground(new java.awt.Color(225, 225, 225,150));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        Menu.add(jPanel3);
        jPanel3.setBounds(90, 0, 1060, 580);

        Fondo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/frame menu.png"))); // NOI18N
        Menu.add(Fondo5);
        Fondo5.setBounds(0, 0, 1160, 650);

        getContentPane().add(Menu);
        Menu.setBounds(0, 0, 1160, 650);

        panel_ingreso.setBackground(new java.awt.Color(255, 255, 255));
        panel_ingreso.setForeground(new java.awt.Color(0, 0, 0));
        panel_ingreso.setLayout(null);

        jTextField1.setText("jTextField1");
        panel_ingreso.add(jTextField1);
        jTextField1.setBounds(60, 360, 320, 40);

        jTextField2.setText("jTextField2");
        panel_ingreso.add(jTextField2);
        jTextField2.setBounds(60, 430, 320, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/undraw_welcoming_re_x0qo 1persona.png"))); // NOI18N
        panel_ingreso.add(jLabel2);
        jLabel2.setBounds(70, 10, 250, 310);

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        panel_ingreso.add(jButton1);
        jButton1.setBounds(150, 500, 120, 50);

        getContentPane().add(panel_ingreso);
        panel_ingreso.setBounds(380, 30, 420, 580);

        Fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/fondo estatico.png"))); // NOI18N
        getContentPane().add(Fondo2);
        Fondo2.setBounds(0, 0, 1160, 648);

        Fondo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/continuacion-animacion_1.gif"))); // NOI18N
        getContentPane().add(Fondo4);
        Fondo4.setBounds(-3, -4, 1160, 650);

        Fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/fondo_animado_login.gif"))); // NOI18N
        getContentPane().add(Fondo3);
        Fondo3.setBounds(0, -10, 1170, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Fondo2.setVisible(false);
        Fondo4.setVisible(true);
        panel_ingreso.setVisible(false);
        Cambio_Ecena_Menu cmm = new Cambio_Ecena_Menu(Fondo4,Fondo5 ,Menu);
        cmm.start();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loggin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo2;
    private javax.swing.JLabel Fondo3;
    private javax.swing.JLabel Fondo4;
    private javax.swing.JLabel Fondo5;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel panel_ingreso;
    // End of variables declaration//GEN-END:variables
}
